const SET_FAVORITE_ADS = 'SET_FAVORITE_ADS';
const SET_LOADING = 'SET_LOADING_FAVORITE_ADS';
const DELETE_FAVORITE_AD = 'DELETE_FAVORITE_AD';

export { SET_FAVORITE_ADS, SET_LOADING, DELETE_FAVORITE_AD };
