const SET_SERVICES = 'SET_SERVICE_SERVICES';
const SET_CATEGORIES = 'SET_SERVICE_CATEGORIES';
const SET_LOADING = 'SET_SERVICE_LOADING';
const SET_FILTER = 'SET_SERVICE_FILTER';

export { SET_SERVICES, SET_CATEGORIES, SET_LOADING, SET_FILTER };
