const SET_EVENTS_LIST = 'SET_EVENTS_LIST';
const SET_EVENTS_DETAIL = 'SET_EVENTS_DETAIL';
const SET_FILTER = 'SET_EVENTS_FILTER';
const SET_CATEGORIES = 'SET_EVENTS_CATEGORIES';
const SET_LOADING = 'SET_EVENTS_LOADING';

export {
  SET_EVENTS_LIST,
  SET_EVENTS_DETAIL,
  SET_FILTER,
  SET_CATEGORIES,
  SET_LOADING,
};
