const SET_FAQ_LIST = 'SET_FAQ_LIST';
const SET_CATEGORIES = 'SET_FAQ_CATEGORIES';
const SET_LOADING = 'SET_FAQ_LOADING';
const SET_FILTER = 'SET_FAQ_FILTER';
const SET_FAQ_DETAIL = 'SET_FAQ_DETAIL';

export {
  SET_FAQ_LIST,
  SET_CATEGORIES,
  SET_LOADING,
  SET_FILTER,
  SET_FAQ_DETAIL,
};
