const SET_LIST = 'SET_NEWS_LIST';
const SET_DETAIL = 'SET_NEWS_DETAIL';
const SET_FILTER = 'SET_NEWS_FILTER';
const SET_CATEGORIES = 'SET_NEWS_CATEGORIES';
const SET_LOADING = 'SET_NEWS_LOADING';

export { SET_LIST, SET_DETAIL, SET_FILTER, SET_CATEGORIES, SET_LOADING };
