const SET_LIST = 'SET_ADS_LIST';
const SET_CATEGORIES = 'SET_ADS_CATEGORIES';
const SET_FILTER = 'SET_ADS_FILTER';
const SET_LOADING = 'SET_ADS_LOADING';
const SET_LOAD_MORE = 'SET_ADS_LOAD_MORE';
const SET_ADS_TO_FAVORITE = 'SET_ADS_TO_FAVORITES_LIST';
const SET_CATEGORIES_LOAD_MORE = 'SET_CATEGORIES_LOAD_MORE';

export {
  SET_LIST,
  SET_CATEGORIES,
  SET_FILTER,
  SET_LOAD_MORE,
  SET_LOADING,
  SET_ADS_TO_FAVORITE,
  SET_CATEGORIES_LOAD_MORE,
};
